spring:
  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1/qxr-erp?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9999
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
mybatis:
  type-aliases-package: com.qxr
  mapper-locations: classpath:/mapping/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
